version: '3'

services:
  educom-mysql:
    image: mysql:8.0
    container_name: educom-mysql
    security_opt:
      - seccomp:unconfined
    env_file:
      - educom.env
    environment:
         - MYSQL_ROOT_PASSWORD= ${MYSQL_ROOT_PASSWORD}
         - MYSQL_DATABASE= ${MYSQL_DATABASE}
         - MYSQL_USER= ${MYSQL_USER}
         - MYSQL_PASSWORD= ${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - educomdb:/var/lib/mysql
    networks:
     - backendnetwork

  educombackend:
    build:
      context: .
      dockerfile: Dockerfile
#    image: adoptopenjdk/openjdk11:alpine-jre
    container_name: educombackend
    security_opt:
      - seccomp:unconfined
    depends_on:
      - educom-mysql
    ports:
      - 8082:8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://educom-mysql:3306/educomdb?SSL=false
      SPRING_DATASOURCE_USERNAME: educomuser
      SPRING_DATASOURCE_PASSWORD: root
    volumes:
      - ./target/educom-0.0.1-SNAPSHOT.jar:/educombackend.jar
#    command: ["java", "-jar", "educombackend.jar"]
    networks:
      - backendnetwork
    links:
      - educom-mysql
volumes:
  educomdb:
networks:
 backendnetwork:


