version: '3'

services:
  educom-mysql:
    image: mysql:8.0
    container_name: educom-mysql
    security_opt:
      - seccomp:unconfined
    environment:
       MYSQL_ROOT_PASSWORD: educom
       MYSQL_DATABASE: educomdb
       MYSQL_USER: educomuser
       MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - educomdb:/var/lib/mysql
#    networks:
#      - educomNetwork

  educombackend:
    build:
      context: .
      dockerfile: Dockerfile
#    image: adoptopenjdk/openjdk11:alpine-jre
    container_name: educombackend
    security_opt:
      - seccomp:unconfined
    depends_on:
      - educom-mysql
    ports:
      - 8082:8082
    environment:
      MYSQL_USER: educomuser
      MYSQL_PASSWORD: root
    volumes:
      - ./target/educom-0.0.1-SNAPSHOT.jar:/educombackend.jar
#    command: ["java", "-jar", "educombackend.jar"]
#    networks:
#      - educomNetwork
    links:
      - educom-mysql
volumes:
  educomdb:
#networks:
#  backendNetwork:


