version: '3'

services:
  educom-mysql:
    image: mysql:8.0
    container_name: educom-mysql
    environment:
       MYSQL_ROOT_PASSWORD: educom
       MYSQL_DATABASE: educomdb
       MYSQL_USER: educomuser
       MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - educomdb:/var/lib/mysql
#    networks:
#      - educomNetwork

  educombackend:
    image: adoptopenjdk/openjdk11:alpine-jre
    container_name: educombackend
    ports:
      - 8082:8082
    depends_on:
      - educom-mysql
    volumes:
      - ./target/educom-0.0.1-SNAPSHOT.jar:/educombackend.jar
    command: ["java", "-jar", "educombackend.jar"]
#    networks:
#      - educomNetwork
volumes:
  educomdb:
#networks:
#  backendNetwork:


