create table educom_user
(
    id        bigint       not null
        constraint educom_user_pkey
            primary key,
    active    boolean      not null,
    email     varchar(120) not null
        constraint uk_ljhi5idjyy5vfbyml9b5ck209
            unique,
    password  varchar(255) not null
        constraint uk_8qoqdgumfx82hhhurdtt2orph
            unique,
    user_name varchar(50)  not null
);

alter table educom_user
    owner to postgres;

create table roles
(
    id   integer generated by default as identity
        constraint roles_pkey
            primary key,
    name varchar(20)
);

alter table roles
    owner to postgres;

create table user_roles
(
    user_id bigint  not null
        constraint fkas08rsfwui9xxdkh3ogub80j9
            references educom_user,
    role_id integer not null
        constraint fkh8ciramu9cc9q3qcqiv4ue8a6
            references roles,
    constraint user_roles_pkey
        primary key (user_id, role_id)
);

alter table user_roles
    owner to postgres;

create table bemerkung
(
    id   bigint not null
        constraint bemerkung_pkey
            primary key,
    name varchar(255)
);

alter table bemerkung
    owner to postgres;

create table lehre
(
    id                         bigint not null
        constraint lehre_pkey
            primary key,
    adresse                    varchar(255),
    email                      varchar(255),
    first_name                 varchar(255),
    geburst_datum              date,
    gender                     varchar(255),
    land                       varchar(255),
    last_name                  varchar(255),
    phone_number               varchar(255),
    plz                        varchar(255),
    stadt                      varchar(255),
    stunden_lohn               double precision,
    verfugbarkeit_fur_lehre_id bigint
);

alter table lehre
    owner to postgres;

create table person_type
(
    id        bigint not null
        constraint person_type_pkey
            primary key,
    type_name integer
);

alter table person_type
    owner to postgres;

create table schule
(
    id          bigint       not null
        constraint schule_pkey
            primary key,
    schule_name varchar(255) not null
);

alter table schule
    owner to postgres;

create table verfugbarkeit_fur_lehre
(
    id                     bigint not null
        constraint verfugbarkeit_fur_lehre_pkey
            primary key,
    verfugbaerkeit_zeit_ab timestamp,
    verfugbar_datum_ab     timestamp,
    verfugbar_datum_bis    timestamp,
    verfugberkeit_zeit_bis timestamp,
    lehre_id               bigint
        constraint fkrpmur9dc3mcuud6lrvxwye11a
            references lehre
);

alter table verfugbarkeit_fur_lehre
    owner to postgres;

alter table lehre
    add constraint fkqercj90vqenj8y6w1ewjeepxs
        foreign key (verfugbarkeit_fur_lehre_id) references verfugbarkeit_fur_lehre;

create table kurs
(
    id       bigint       not null
        constraint kurs_pkey
            primary key,
    anfangab date,
    dauer    integer      not null,
    endebis  date,
    kosten   double precision,
    kurslang integer      not null,
    kurstype varchar(255),
    name     varchar(255) not null,
    raum     varchar(255),
    lehre_id bigint
        constraint fknb583eump79wv1jwp0a0ml676
            references lehre
);

alter table kurs
    owner to postgres;

create table lehre_kanngeben
(
    lehre_id     bigint not null
        constraint fkief8x04bwy8k0w741v1er900
            references lehre,
    kanngeben_id bigint not null
        constraint uk_f95dn7jyh9pua4cf2nwuuoehi
            unique
        constraint fkoop3tn6oqs0r1ent2m7dq7d0m
            references kurs
);

alter table lehre_kanngeben
    owner to postgres;

create table schuler
(
    id            bigint not null
        constraint schuler_pkey
            primary key,
    adresse       varchar(255),
    email         varchar(255),
    first_name    varchar(255),
    geburst_datum date,
    gender        varchar(255),
    land          varchar(255),
    last_name     varchar(255),
    phone_number  varchar(255),
    plz           varchar(255),
    stadt         varchar(255),
    klasse        varchar(255),
    mutter        varchar(255),
    vater         varchar(255),
    schule_id     bigint
        constraint fknk8stgluib49j2uicmbyadfau
            references schule
);

alter table schuler
    owner to postgres;

create table anmeldung
(
    schuler_id bigint not null
        constraint fk8nkfitc9d2e9kh66guupm6vy9
            references schuler,
    kurs_id    bigint not null
        constraint fk5kg5w9mkunlo4xwktufai8hwh
            references kurs,
    constraint anmeldung_pkey
        primary key (schuler_id, kurs_id)
);

alter table anmeldung
    owner to postgres;

create table stunden_plan
(
    id         bigint not null
        constraint stunden_plan_pkey
            primary key,
    beginn     time,
    datum      date,
    ende       time,
    raum       varchar(255),
    vertretung boolean,
    kurs_id    bigint
        constraint fkh7fj8546n6om8pm0oabwwudwl
            references kurs
);

alter table stunden_plan
    owner to postgres;

create table stunden_plan_details
(
    id                  bigint not null
        constraint stunden_plan_details_pkey
            primary key,
    anwesend            boolean,
    speate_anfang       boolean,
    speate_teilname_min double precision,
    schuler_id          bigint
        constraint fkk173cd6i8k1hecaew06ibu9f2
            references schuler,
    stunden_plan_id     bigint
        constraint fkmmi21v5m8e75ba1ua51y6ibbw
            references stunden_plan,
    details_id          bigint not null
        constraint uk_ak7at9htc7chj452rmid2gqr1
            unique
        constraint fk8hapm0ocikgwpf9ghyqu6ry08
            references stunden_plan_details
);

alter table stunden_plan_details
    owner to postgres;

create table stunden_plan_details_bemerkungen
(
    stunden_plan_details_id bigint not null
        constraint fk6m1yx6x4844vprqlib1f2ovlc
            references stunden_plan_details,
    bemerkungen_id          bigint not null
        constraint uk_gfpljtpjlel86jouy29gs3o7y
            unique
        constraint fkg7qij84u2mefibwp8u6r2gcjn
            references bemerkung,
    constraint stunden_plan_details_bemerkungen_pkey
        primary key (stunden_plan_details_id, bemerkungen_id)
);

alter table stunden_plan_details_bemerkungen
    owner to postgres;

create table vertrag
(
    id               bigint  not null
        constraint vertrag_pkey
            primary key,
    anmeldegebuhr    double precision,
    einmalige_kosten double precision,
    materialprice    double precision,
    monatlische_rate double precision,
    rabat            integer not null,
    rabat_percent    integer not null,
    restbetrag       double precision,
    summe            double precision,
    vertragsbegin    date,
    vertragsdatum    timestamp,
    vertragsende     date,
    zahlungstype     integer
);

alter table vertrag
    owner to postgres;

create table vertrag_schueler
(
    schuler_id bigint
        constraint fkc4x4jim1ik5aen8gpc905uq0w
            references schuler,
    vertrag_id bigint not null
        constraint vertrag_schueler_pkey
            primary key
        constraint fk5rby73kxobbi5ddgs1tqgeead
            references vertrag
);

alter table vertrag_schueler
    owner to postgres;

