INSERT INTO public.roles (id, name) VALUES (1, 'ROLE_USER');
INSERT INTO public.educom_user (id, active, email, password, user_name) VALUES (38, true, 'cckk@cck', '$2a$10$0KFKh1..VZkno/AlFdD0Z.3Jn.bj3cuTGbiVqJjqxs74LUZJvuLPG', 'c');
INSERT INTO public.educom_user (id, active, email, password, user_name) VALUES (72, true, 'cemilkabakci@gmail.com', '$2a$10$pucerHqeZ/hhVqCekd4eiefxtKIpmizcx2ntKHPHC8.X/kmXHkcKy', 'cckk');
INSERT INTO public.educom_user (id, active, email, password, user_name) VALUES (73, true, 'cemil@gmail.com', '$2a$10$2hBJ5Gq/UFfYllN.cEEd5OVMnbHWnHXm914FBw8eyXIJ8RBkSzzJi', 'cemil');
INSERT INTO public.educom_user (id, active, email, password, user_name) VALUES (74, true, 'dddd', '$2a$10$iEwXQWzr1aCKplfoFs6Dz.kmarDrFkLdbjywqKzVzCoyHR52NYfTe', 'dd');
INSERT INTO public.educom_user (id, active, email, password, user_name) VALUES (75, true, 'cemoli@cemoli', '$2a$10$a6kupA/o9z8Aq36xgm1J7u1b9cz/IX2GA0vj7HHhrEMX6HwSFqwhS', 'cemoli');
INSERT INTO public.educom_user (id, active, email, password, user_name) VALUES (76, true, 'kabakci@kgmail', '$2a$10$ZsDypXS1CZSVAOq1oxL1U.8FQ1.I21S5WwOjdAX1mLDIt8eFaewFa', 'kabakci');
INSERT INTO public.educom_user (id, active, email, password, user_name) VALUES (77, true, 'memoli@df', '$2a$10$synX9Od0iN2Bm51qzLPpsO68GMmgRQmxtkIA3XFS4yact9ScpQPuy', 'memoli');
INSERT INTO public.user_roles (user_id, role_id) VALUES (38, 1);
INSERT INTO public.user_roles (user_id, role_id) VALUES (72, 1);
INSERT INTO public.user_roles (user_id, role_id) VALUES (73, 1);
INSERT INTO public.user_roles (user_id, role_id) VALUES (74, 1);
INSERT INTO public.user_roles (user_id, role_id) VALUES (75, 1);
INSERT INTO public.user_roles (user_id, role_id) VALUES (76, 1);
INSERT INTO public.user_roles (user_id, role_id) VALUES (77, 1);